### ISSUE TITLE
find_two_that_sum_test.go unexpected behaviour

### ISSUE THREAD

**Issue by gustavohmsilva** [joncalhoun/algorithmswithgo.com#5]
So, I was in the FindTwoThatSum exercise and at first I though I was doing something wrong with my approach but after watching your solution and replicating it exactly, I found that the error persists for both, your and mine solution, which points for something in the go test file or something to do with the golang version I'm using (I'm on 1.14) maybe:

Algorithms tested:
**Yours:**
```
func FindTwoThatSum(numbers []int, sum int) (int, int) {
	for i, val := range numbers {
		for j, val2 := range numbers {
			if i == j {
				continue
			}
			if val+val2 == sum {
				return val, val2
			}
		}
	}
	return -1, -1
}
```
**Mine:**
```
func FindTwoThatSum(numbers []int, sum int) (int, int) {
	for i, val := range numbers[:len(numbers)-1] {
		for _, val2 := range numbers[i+1:] {
			if val+val2 == sum {
				return val, val2
			}
		}
	}
	return -1, -1
}
```

**Error** _(both give the same FAIL message, varying a little regarding the testing.go line)_:
```
--- FAIL: TestFindTwoThatSum (0.00s)
    --- FAIL: TestFindTwoThatSum/[1_2_3_4]_with_sum_7 (0.00s)
panic: runtime error: index out of range [4] with length 4 [recovered]
        panic: runtime error: index out of range [4] with length 4

goroutine 7 [running]:
testing.tRunner.func1.1(0x536ca0, 0xc0000185c0)
        /usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc000124240)
        /usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0x536ca0, 0xc0000185c0)
        /usr/local/go/src/runtime/panic.go:967 +0x15d
algo/module01.TestFindTwoThatSum.func1(0xc000124240)
        /home/john/go/src/github.com/joncalhoun/algorithmswithgo.com/module01/find_two_that_sum_test.go:42 +0x46e
testing.tRunner(0xc000124240, 0xc00005e520)
        /usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1043 +0x357
exit status 2
FAIL    algo/module01   0.003s
```

**Comment by joncalhoun** [comment]
You are returning values, not the indices of them. The solution returns indices as far as I can tell looking in the solutions directory, and I believe that code is an exact replica of the videos code.
